name: CI/CD Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Stage 1 - Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build
        run: echo "Building the application..."

  test:
    name: Stage 2 - Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Tests
        run: echo "Running tests..."

  deploy:
    name: Stage 3 - Deploy (Manual Approval)
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo "[+] Pulling latest code from GitHub..."
            cd /home/ubuntu/git-github
            git pull origin main
            git reset --hard origin/main

            echo "[+] Killing any existing process on port 8000..."
            fuser -k 8000/tcp || true

            echo "[+] Starting Python app in background..."
            nohup python3 app/main.py > app.log 2>&1 &

            echo "[+] Deployment complete. App should be live at http://${{ secrets.EC2_HOST }}:8000"
